/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  static const String PLUGIN_NAME = 'composant';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String FLUTTER = 'assets/images/flutter.jpeg';
  static const String LOGOV2 = 'assets/images/logov2.png';
  static const String TRIP = 'assets/images/trip.jpg';
}
